dotfiles:
  - .zshrc
  - .gitignore_global
  - .config/devbox.zsh
  - .config/theme.zsh
  - .config/functions.zsh
  - .config/aliases.zsh
  - .config/karabiner/karabiner.json
  - .config/sheldon/plugins.toml
