dotfiles:
  - .zshrc
  - .zprofile
  - .gitignore_global
  - Library/Application Support/com.mitchellh.ghostty/config
  - .config/devbox.zsh
  - .config/theme.zsh
  - .config/functions.zsh
  - .config/aliases.zsh
  - .config/karabiner/karabiner.json
  - .config/sheldon/plugins.toml
  - .local/share/devbox/global/default/devbox.json
  - .local/share/devbox/global/default/devbox.lock
