# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

[plugins.completions]
github = "zsh-users/zsh-completions"
tag = "0.35.0"

[plugins.autosuggestions]
github = "zsh-users/zsh-autosuggestions"
tag = "v0.7.1"

[plugins.substring]
github = "zsh-users/zsh-history-substring-search"
tag = "v1.1.0"

[plugins.highlighting]
github = "zsh-users/zsh-syntax-highlighting"
tag = "0.8.0"

[plugins.zoxide]
github = "ajeetdsouza/zoxide"
tag = "v0.9.5"
